CREATE TABLE users {
  user id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE ,
  password VARCHAR(300) NOT NULL,
  role ENUM('ADMIN','DOCTOR','STAFF'),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

/* ('NIHAL123#','NIHAL','ADMIN')*/
